### ISSUE TITLE
Clippy action doesn't work

### ISSUE THREAD

**Issue by yoshuawuyts** [bltavares/actions#27]
When running:
```yaml

name: PR Review
on: [pull_request_review]

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Run Clippy
        uses: bltavares/actions/clippy@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "autofix"
```
I get the output:
```txt

2019-08-25T23:12:00.1377418Z ##[group]Run bltavares/actions/clippy@master
2019-08-25T23:12:00.1453979Z with:
2019-08-25T23:12:00.1454073Z   args: autofix
2019-08-25T23:12:00.1454143Z env:
2019-08-25T23:12:00.1454295Z   GITHUB_TOKEN: ***
2019-08-25T23:12:00.1454346Z ##[endgroup]
2019-08-25T23:12:00.1792782Z ##[command]/usr/bin/docker run --name fe0f7ee54c96b9554861bdaedbbe4553ba06_259693 --label 29fe0f --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/{omitted}/{omitted}":"/github/workspace" 29fe0f:7ee54c96b9554861bdaedbbe4553ba06 autofix
2019-08-25T23:12:00.7708717Z error: could not find `Cargo.toml` in `/github/workspace` or any parent directory
2019-08-25T23:12:01.1514235Z ##[error]Docker run failed with exit code 101
2019-08-25T23:12:01.1641246Z Cleaning up orphan processes
